# insult.py

import random

# Metadata

NAME    = 'insult'
ENABLE  = True
PATTERN = r'^!insult ?(?P<nick>[^\s]*)'
USAGE   = '''Usage: !insult [nick]
Hurls insults. Optionally insults a specific user
'''


# soy bad i stole these from here: https://raw.githubusercontent.com/knivey/lolbot/master/scripts/insult/insult.php
INSULTS = [
    "roasted",
    "u have no bad bitches",
    "cope",
    "don't care",
    "didn't ask",
    "ratio'd",
    "take the L",
    "u fell off",
    "i rejected your mom's advances",
    "die mad",
    "copium",
    "touch grass",
    "unsubbed",
    "hoes mad",
    "u look like u sit on public toilets",
    "u take yr socks off on airplanes",
    "yr friends have a group chat w/o you",
    "hope u die",
    "simp",
    "your parents are cousins",
    "cancelled",
    "ez clap",
    "not funny didn't laugh",
    "go outside",
    "irrelevant",
    "don't care anymore",
    "low T",
    "yr sister sucked my dick",
    "u huff airhorn gas",
    "your asciis suck",
    "yr house burned down",
    "yr parents are divorced",
    "u wear trenchcoats",
    "your teeth are gross",
    "u will die alone",
    "u sleep on an air mattress",
    "yr youtube channel gets no views",
    "u were born with herpes",
    "yr mom is attracted to u",
    "yr memes suck",
    "u still watch toy story",
    "u were born from a threesome",
    "your links r 404",
    "lol neck beard",
    "u like zelda memes",
    "you're balding",
    "sisqo wouldn't even like your thong",
    "u watch the big bang theory",
    "u use microsoft office on linux",
    "u buy every new iphone",
    "u think nfts are cool",
    "transitioned & regret it",
    "u pay for pornhub",
    "u buy tokens on cam sites",
    "u pay for spotify",
    "u pay for youtube premium",
    "u have a favorite commercial",
    "u can barely swim",
    "u smell like hotdog water",
    "u use electron apps",
    "u wake up and check your likes on instagram",
    "ur memes r old",
    "u still wear covid masks",
    "u watch bra reviews on youtube",
    "the only smores u had were from a microwave",
    "u own collectibles",
    "u wear a bath robe",
    "u use http for banking",
    "ur low on vitamins",
    "proactiv didnt work for u",
    "ur parents are poly",
    "u have a favorite minion",
    "all ur memes are deepfried",
    "stay inside + the world doesnt want to see u",
    "never grilled corn",
    "u drink coors lite (gross)",
    "u eat boiled bologna + u smell like train smoke + ur a hobo",
    "u talk to birds",
    "u wear rags",
    "u work at a gas station",
    "you blame black folk for ruining your life",
    "you eat free ham",
    "you have garage sales",
    "not clicking",
    "your arms have extra skin",
    "you watch work out vids while eating donuts",
    "you save forums as a pdf",
    "micropenis",
    "grey at 30",
    "first-name basis at arbys",
    "car infested with squirrels",
    "you dont even skate",
    "you live in a yurt",
    "fat as fuck",
    "car full of fast food waste",
    "u sell your diabete meds",
    "you're a furry",
    "no one talks to u on omegle",
    "u bought fake kratom",
    "overdosed on herbal ecstasy",
    "army recruiter won't return your calls",
    "ur name means hummus in hebrew",
    "slipknot",
    "u browse dating sites",
    "you use cheap toilet paper",
    "your typing is ass",
    "clammy skin",
    "ur house has roaches",
    "u pay for cable",
    "your fridge is loud",
    "you got 8 booster shots",
    "you use signal on windows",
    "feminine thumbs",
    "stinky socks",
    "u use telegram",
    "u pay extra for oil changes",
    "u watch tv with an antenna",
    "special education",
    "missing keys on your keyboard",
    "cheap cologne",
    "you use hotmail",
    "you use yahoo for email",
    "u listen to asmr",
    "u use library internet",
    "u watch yoga pants vids",
    "u listen to pickup artist tutorials",
    "u smell like onions",
    "ur an incel",
    "you did gay w/ your brother",
    "no friends",
    "yr mum has aids",
    "dick so small cant even hit the IUD",
    "u have a therapist",
    "the community does not like u",
    "cant bbq",
    "u were supposed to be an abortion",
    "you like furry documentaries",
    "u have a portable dvd player",
    "u drink shitty coffee",
    "u buy cigarettes online",
    "you like elon musk",
    "google has all your data",
    "u love facebook",
    "u draw on money",
    "u watch hentai (weeb)",
    "u wear and use fedora",
    "u went to fyre feast",
    "u cant read sheet music",
    "failed kindergarten",
    "failed the GED test",
    "u buy second hand underwear",
    "u think u 'have a connection' with the stripper",
    "u have mold under your sink",
    "your shower never gets cleaned",
    "u think science is a religion",
    "ur dehydrated",
    "u shower with sister + save hot water",
    "ur muslim",
    "ur christian",
    "ur catholic",
    "u virtue signal on twitter + ur not a good human at all",
    "you wear turtlenecks",
    "you lose money on shitcoins",
    "u stole your sisters gas money",
    "u steal paintings from motels",
    "u use walmart wifi",
    "ur phone has multiple mcdonalds wifi saved",
    "arthritis",
    "u call ppl beta and alpha males",
    "u get horny from gas station magazines",
    "u read articles about celebs",
    "u thought bonzi buddy was ur friend",
    "u miss clippy from microsoft office",
    "u play solitaire",
    "u don't use deodorant",
    "ur fridge has literal garbage in it",
    "u still play pokemon go",
    "u masturbate to bing image results",
    "u talk to mormons that come to your house",
    "u write perl",
    "python sucks",
    "you huff freon from your neighbors AC",
    "your dad fucked my ass",
    "you can't eat solid foods",
    "rsa ssh key",
    "broken startup scripts + you use mac",
    "no1 noticed u were here",
    "u use python2.7",
    "i rejected your dads advances",
    "you leave the tags on your hats",
    "systemd-lover",
    "u make everyone depresed",
    "u still think the n word is funny",
    "u get grounded for torrenting",
    "u paid for windows",
    "u think gmail is innovative",
    "u pay for turbotax",
    "u found ur online therapist thru a facebook ad",
    "u run irssi as root",
    "u still use xorg",
    "u reuse tea bags too many times",
    "u stepped on your own mouse traps",
    "ur dog doesn't even like u",
    "u pretend ur mom is ur step mom",
    "career complainer",
    "u post pics of your weed online",
    "u paid for winrar",
    "u grow carrots",
    "u put your mouth directly on water fountains",
    "u stare at yr screen w/ your jaw slightly ajar",
    "u pull yr pants all the way down @ urinals",
    "u breathe w/ your mouth",
    "u like seagulls (dumb)",
    "u listen to kpop",
    "u use emacs",
    "u breathe loud as fuck",
    "all ur socks have holes",
    "u watch girls volleyball on youtube",
    "u think osama did 9/11",
    "u thought invading iraq was a good idea",
    "u use kde",
    "man boobs lol",
    "your room smells like u",
    "fix your door",
    "your blogs are retarded",
    "you roll your own tobacco",
    "im not strung out enough to chat with u",
    "u think anonymous is cool",
    "u believe popups that say u have a virus",
    "u looked into a pescatarian diet",
    "u use 2fa on porn sites",
    "yr favorite powerup is the frog suit",
    "u browse casual hookups on craigslist",
    "u ask for drugs on craigslist",
    "u own a fleshlight",
    "twitch streamers barely pretend to like u",
    "u take meds every day + judge casual drug users",
    "u swim w/ a t-shirt on",
    "u do this meme all day + get a fucking life",
    "u tried on a burka",
    "u worry about slipping in the shower",
    "caught slippin",
    "u werent breast fed + mom didnt love u",
    "u pre-ordered a steam deck",
    "u treat linux like a cult",
    "your dickhole is small",
    "you buy swords at the mall",
    "your mom fucks your friends",
    "your stepdad does meth",
    "u date girls from omegle",
    "u appeared on a TLC show",
    "u watch TLC shows",
    "ur application to be on jerry springer was rejected",
    "u got a DNA test for all of ur children",
    "ur mom chugs hand sanitizer",
    "u shave yr face w/ the razor ur gf uses for her pits",
    "u think clocks give u the exact time",
    "u like windows 11",
    "u suffer from jaundice",
    "u sleep thru home invasions",
    "u drink diet grocery store brand cola",
    "u watch sports",
    "u like wrestling",
    "u still wear your highschool football jersey",
    "you talk about vim on the first date",
    "yr mom reminds u that u ruined her life constantly",
    "your grandma is 40",
    "the whole trailer park loves your sister",
    "u nair your balls",
    "u spilled beard oil in your instant noodles",
    "u enjoy prostate exams",
    "u wipe boogers on your wall",
    "u punch holes in your walls",
    "u have velcro shoes but still tie them",
    "u bought a hardware wallet off ebay/craigslist",
    "your lawn mower will not obey u",
    "u converted a bag into a felony",
    "u use email.com",
    "u think asmr is a type of encryption",
    "u have coffee stains on your car title",
    "u bought a timeshare",
    "cant afford a costco membership",
    "u borrow netflix passwords every 3 weeks",
    "u sit on couches at the mall waiting for ur girl to shop",
    "u eat maggot cheese",
    "u clap off beat at concerts",
    "u proposed to ur fleshlight and it said no",
    "u shit in the shower",
    "skechers",
    "u think wrestling is real",
    "you've played world of warcraft",
    "u think dmt is more meaningful if u go in the jungle w/ a guy in a costume",
    "u use lime scooters and bring a helmet",
    "u borrow tobacco",
    "yr primary vehicle is bicycle + your kid has a car",
    "you 'invest' in audio gear",
    "you wear safety glasses doing routine household maintenance",
    "you've never broken a bone (pussy)",
    "your cat thinks you're weird (u are)",
    "u lose 1 player games on the easiest mode",
    "stripper gave ur money back",
    "u like japanese culture a little too much",
    "u play MMOs completely alone",
    "ur dad has a man bun",
    "laptop charger only works at a certain angle",
    "u mounted a sword on your wall",
    "u like kfc",
    "u made mac w/ no cheese",
    "u smell yr hand after scratching yr balls",
    "u eat fistfuls of dry breakfast cereal on the bus",
    "u have a dog walking business",
    "u sweat for no reason",
    "u have diabetes",
    "sugar makes u pass out",
    "jacked off to 9/11",
    "u watch the same 3 tv shows on repeat",
    "u buy store brand ranch dorito knock offs",
    "u buy chicken from gas stations",
    "u think tor is safe",
    "u feel like u could succeed one day",
    "u get high on beer",
    "u check behind the shower curtain even tho u are not taking a shower + scared",
    "u bought nordvpn from a youtuber",
    "u had a pony tail once",
    "u think six feet deep is a foot fetish thing",
    "ur parents claim u as a dependent on their taxes",
    "u buy $400 keyboards",
    "u use an hp pavilion",
    "u use a dell inspiron",
    "u still listen to aqua",
    "u live in ur car",
    "u think oranges are exotic",
    "u play league of legends",
    "u like apple products",
    "u have a permanent kali linux install",
    "u use efnet",
    "u wash your face after your pits",
    "your feet are dirty",
    "u think gang stalking is real + u smoke meth",
    "u think u have a paul wall poster but it is ali G",
    "u have corona virus",
    "u still believe in 6ft distancing",
    "u watch rowing videos",
    "u have a music shelf in your house",
    "u have a rust t-shirt",
    "u have a github sticker on your laptop",
    "u steal cutlery from continental hotel breakfasts",
    "u hunt humans on isolated islands for fun",
    "woke up late",
    "depressed",
    "u bought a course on linux from a hindi on udemy",
    "u hide behind teh shower curtain during home invasions",
    "u have shitty genes",
    "ur white",
    "u never left the place u were born",
    "u take antidepresants",
    "nobody gave u a gmail invite",
    "u want a guy to buy u dinner but cant even ask",
    "u let ur friend tattoo your face for practice",
    "u lie about being vegan",
    "ur handjobs are better than ur blowjobs",
    "u tell everyone ur writing a book but u wrote 2 pages",
    "u have murder charges in another country",
    "u enjoy chain smoking",
    "you had a positive childhood",
    "u still believe in bitcoin",
    "u talk about arch linux to women you meet at the bus stop",
    "u drive a car with multi color panels",
    "your favorite shopping trips are to the grocery store",
    "u bought every book oprah suggested",
    "u have abnormal facial features",
    "u have poor reasoning & judgment",
    "u are too pale to ride the rollercoaster",
    "your mom has a dragon tattoo",
    "u did a dance w/ your tribe but the rain gods hate u",
    "u went to a town hall meeting and they cut your mic off",
    "u complain to HOA about your neighbors christmas lights",
    "u havent cooked your own food in over a year",
    "look like a karen despite being a man",
    "u like van life videos",
    "u nod your head irl while the youtuber says stuff u agree with",
    "u think running train on a girl is literally running her over w/ a train",
    "u tip at drivethrus",
    "u wear clothes from before 9/11",
    "u get along with texans",
    "u support america",
    "u think nyc has good food",
    "u use filezilla",
    "u use hexchat",
    "u still use a compaq",
    "u liked windows ME",
    "belly button lint",
    "u get winded walking up 8 stairs",
    "a bum gave u change",
    "u save expired coupons",
    "stamp collector",
    "u flirt with delivery people",
    "ur part of an mlm",
    "you believe every conspiracy theory presented to u",
    "ur a mod on reddit",
    "ur a mod on discord",
    "u follow and unfollow people on social media",
    "u buy dinner from 7/11",
    "u admire fictional characters",
    "u like near beer",
    "u think egypt has ancient shit",
    "u take cbd for pain",
    "u believe in democracy",
    "rear ended your own car",
    "you have a wonderful life and no one to share it with",
    "u went to an islamic country and wanted to get 'stoned'",
    "u have a favorite kardashian",
    "u prolly get no dick",
    "u got fired on your day off",
    "u use towels as curtains",
    "u smoke clove cigarettes",
    "u tried to run apt on arch",
    "u blame isis for yr relationship problems",
    "u confessed to a priest lmao",
    "u smell like freshly cut grass",
    "your wife wore a paintsuit to your wedding",
    "u enjoy a life of insignificance",
]

# Command

async def insult(bot, message, nick=None):
    
    # choose 5-8 insults
    insults = []
    for _ in range(random.randint(6,9)):
        insults.append(random.choice(INSULTS))
    
    insult = " + ".join(insults)
    
    # add a nick
    if nick:
        insult = nick + ": " + insult
        
    return message.with_body(insult)

# Register

def register(bot):
    return (
        ('command', PATTERN, insult),
    )

# vim: set sts=4 sw=4 ts=8 expandtab ft=python:
