name: tests
on:
  push:
    branches: [ bobbit-0.2.x ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ bobbit-0.2.x ]


jobs:
  build:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installs dependencies
        run: |
          python3 -m pip install -r requirements.txt
      
      - name: Install and run Pylint
        run: |
          python3 -m pip install pylint 
          # Only will fail for actual errors
          python3 -m pylint src/ -d "W,C,R"

      - name: Runs tests
        run: |
          python3 -m unittest 
